# Generated by Django 3.1.2 on 2020-10-12 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='choiceText',
            new_name='choice_text',
        ),
    ]
